#!/bin/sh

# RBL Check by Zenith Media Canada
# Created by Jon Wong
# alpha version
# will include email notification on detection for automated checks
# rbls listed are based on research and reputation
# this script will accept IP address and then find the reverse ptr and check the domain on another dbl to confirm no rbl association.

BLISTS="
    cbl.abuseat.org
    bl.spamcop.net
    b.barracudacentral.org
    dnsbl-1.uceprotect.net
    psbl.surriel.com
    dnsbl.sorbs.net
    spam.dnsbl.sorbs.net
    zen.spamhaus.org
    bcl.spamhaus.org
    pbl.spamhaus.org
    sbl.spamhaus.org
    xbl.spamhaus.org
    swl.spamhaus.org
    multi.surbl.org
    iadb.isipp.com
    ips.backscatterer.org
    hostkarma.junkemailfilter.com
    aspews.ext.sorbs.net
"
## removed
#multi.uribl.com
# hostkarma.junkemailfilter.com is a white list, create a new section for whitelists
DLISTS="
    dbl.spamhaus.org
    nobl.junkemailfilter.com
    ubl.nszones.com
    uribl.spameatingmonkey.net
    hostkarma.junkemailfilter.com
"
WLIST=""

# URL SOURCE
# http://cbl.abuseat.org
# http://www.spamcop.net/fom-serve/cache/351.html
# http://barracudacentral.org/rbl/how-to-use
# 
# http://spameatingmonkey.com

# White Lists
# 
# simple shell function to show an error message and exit
#  $0  : the name of shell script, $1 is the string passed as argument
# >&2  : redirect/send the message to stderr

ERROR() {
  echo $0 ERROR: $1 >&2
  exit 2
}

# -- Sanity check on parameters
[ $# -ne 1 ] && ERROR 'Please specify a single IP address'

reverse=$(echo $1 |
  sed -ne "s~^\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)$~\4.\3.\2.\1~p")

if [ "x${reverse}" = "x" ] ; then
      ERROR  "IMHO '$1' doesn't look like a valid IP address"
      exit 1
fi

RDNS=$(dig +short -x $1)

printf "\n"
printf "Searching for $1 on IP Based Black Lists \n"
for BL in ${BLISTS} ; do
    #printf $(env TZ=UTC date "+%Y-%m-%d_%H:%M:%S_%Z")
    printf "%-40s" " ${reverse}.${BL}."
    IPL="$(dig @8.8.8.8 +short -t a ${reverse}.${BL}.)"
    IPT="$(dig @8.8.4.4 +short -t txt ${reverse}.${BL}.)"
    echo ${IPL:----} ${IPT:----}
done

printf "\n"
printf "Searching for ${RDNS} on Domain Based Black Lists \n"
for DL in ${DLISTS} ; do
     printf "%-40s" " ${RDNS}${DL}."
     DNL="$(dig @8.8.8.8 +short ${RDNS}${DL}.)"
     DNT="$(dig @8.8.4.4 +short TXT ${RDNS}${DL}.)"
     echo ${DNL:----} ${DNT:----}
done
printf "\n"

#echo ''
#echo SPAM Legend:
#echo ''
#echo CBL .0.2 -- Possible SPAM
#echo SpamCOP -- Possible SPAM
#echo Barracuda 0.2 -- Possible SPAM
#echo UCProtect 0.2 -- Possible SPAM
#echo ''
#echo Sorbs Combined -- Informational
#echo HTTP -- 0.2 SOCKS -- 0.3
#echo Misc -- 0.4 SMTP -- 0.5
#echo WEB -- 0.7 Block -- 0.8
#echo ZOMBIE -- 0.9 DUL -- 0.10
#echo BADCONF -- 0.11 NOMAIL -- 0.12
#echo Sorbs SPAM - 0.6
#echo ''
#echo ZEN Combined -- Informational
#echo BCL IP Null Route -- Not implimented
#echo DBL Domain Blick List -- Not implimented 
#echo PBL Dynamic IP 0.10-11 -- Informational
#echo SBL Block List -- 0.2 Possible SPAM -- CSS Snowshoe 0.3
#echo XBL OpenProxy / Trojan -- 0.4-5/6/7 -- Possible Bot Net
#echo SWL IP White List -- NEVER SPAM
#echo SWL 127.0.2.2 -- IP Sending Individual Mail SWL 127.0.2.3 -- IP Sending Transactions
#echo SWL 127.0.2.102 -- IP Sending Individual Mail - Temp SWL 127.0.2.103 -- IP Sending Transactions - Temp
##include DWL for domain white list .2.12-13 112-113 add a 1 above for response
#echo SURB multi list
#echo SpamCop 0.2 - WS 0.4 - AbuseButler 0.32 - PH 0.8 - MW 0.16 - JWSpamSpy 0.64
#echo if on multiple lists add the actet to know what lists they are on.
#echo IADB White List .1 - Listed, .2 - Vouched, .3 - Publishes SPF
#echo full return codes http://www.isipp.com/email-accreditation/list-of-codes/
#echo ''
#echo Additional Information
#echo ''
#ASN="$(dig +short -t txt ${reverse}.origin.asn.cymru.com.)"
#echo ASN -- ${ASN:----}
#using http://www.team-cymru.org/Services/ip-to-asn.html for additional information
#echo Reverse HOSTNAME  ${RDNS:----}
#whois -h whois.cymru.com " -v $1"
#--- EOT ------
